### PR TITLE
Lab3

### PR DESCRIPTION
**Pull request by danilasokratov**
@AdamK42 I think I'm "done" with the lab, but I'm unsure about my methods for the probability/sigma in latter parts of problem 3. I think my understanding of the problem should be outlined quite thoroughly, but let me know what you think. I think I understand "in words/principle" what I should be doing to obtain the probability, but I'm having an issue due to the integration on the probability distribution, similarly to last lab.

### CODE REVIEW

**Comment by AdamK42** [comment]
@danilasokratov I think this one went pretty well, as far as I can tell the thinking is all correct. Since I am actually doing this at a reasonable time today, I'll do the nice formatting like I did for lab 1.

## Problem 1

### A1
*  Probably shouldn't be to sarcastic, though I appreciate what your saying. 
### A4
* I am not entirely sure from the answer field what your numbers are. I can't tell if one of these numbers is supposed to be false negatives or not. I also had difficulty creating the truth table, but it would be nice for the numbers to have some string attached to say what they are.
### C
* I think that your calculation here is probably better suited to section 4A. This is what I was confused by.

## Problem 3

### Question 2
* I think you interpreted the probability wrong. We want to know the significance of the fact that we get a *lower* number of events, which means that we want to know 1 - probability you found. This is because we wanted to see the integral of the distribution from 0 events to 6800, not 6800 to infinity.
### Question 3
* I think you have to multiply sigma by numTotal in order for it to be for the correct distribution. At least, thats what we were doing in lecture 6 on slide 18 to the best of my knowledge. Having said that, that is what I did and I got an absolutely wild sigma so who knows.

**Comment by danilasokratov** [comment]
@AdamK42 I believe cdf integrates from -inf up to the value specified, but I am checking this a bit more thoroughly now.
The slide you referenced is actually checking that the threshold that Prof. Moralles found corresponds to a certain probability, not value of sigma. 1 - cdf(distribution,threshold) would be the probability integrated from the right of the regular distribution up to the adjusted threshold, so then he needs to multiply the (very small resulting probability) by numTrials to get to the actual probability on the convolved (or multiplied) distribution.

**Comment by danilasokratov** [comment]
@AdamK42 https://en.wikipedia.org/wiki/Normal_distribution#Cumulative_distribution_function
With the definition of the integral, I believe my use of cdf is correct. 1-cdf would give the integral from +inf to the value if the probability distribution is normalized.

**Comment by AdamK42** [comment]
I see, that makes sense. cdf works differently for python, so I was just confused. I understand now.

**Comment by AdamK42** [comment]
@danilasokratov  This looks pretty good! Though for the last section, I'm not sure we found that we have low confidence that the moon is effecting out distribution, but rather that the moons impact is low. We know that the moon is the cause due to the wording of the problem.

**Comment by danilasokratov** [comment]
@AdamK42 I think that's just one of the "unique aspects" of this problem that I wanted to discuss.
@sfzhu I think I feel comfortable submitting this now

**Comment by danilasokratov** [comment]
@sfzhu I forgot to mention, I think this took me about 6-7 hours.

**Comment by sfzhu** [comment]
Problem 3 result is wrong, the code should be something like below.
numTotal = 7200;
signal = 6800;
background = makedist("Poisson","lambda", numTotal);
prob = cdf(background,signal)
sigma = icdf('Normal',1-prob,0,1)

The result will be 4.75.

**Pull request merged**
