### PR TITLE
Lab1

### PR DESCRIPTION
**Pull request by danilasokratov**
@AdamK42 I think it's ready! I'm going to change all the nasty %comments to actual text Sunday. The one part I don't feel extremely confident is if my explanation for the latter parts (on the Poisson distribution) is sufficient. What do you think?

### CODE REVIEW

**Review by AdamK42 — COMMENTED** [review]
@danilasokratov, I can't seem to figure out how to view your code. When I tried to pull your repository it only pulled master. I tried git pull -all, but it didn't bring down the branch either. I can't seem to view the code you have provided on git hub and I see no way to download it seperately to comment. I am unsure what to do.

**Comment by danilasokratov** [comment]
Yeah, I'm failing to download your code as well. I'm going to email Shifeng and see if he can do something.

**Comment by AdamK42** [comment]
Sounds good

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by danilasokratov** [comment]
Hey Adam,

Shifeng got back to me, this is the response he provided.

Hi Dan
Here is a link might help.
http://hselab.org/git_newbie_error.html
The other way to solve it is to re-do the process in the following steps.
 1. Fork your partner's project.
 2. Make changes on your page.
 3. pull request.

I'm going to check that later in the evening, but tell me if this fixes your issue.

**Comment by AdamK42** [comment]
@danilasokratov, so I figured out how to pull the branch from the remote repo no problem, but now when I try to open your .mlx file in matlab it fails. I am unsure why because when I clicked on the live editor requirements, I see that I meet all of them. However, if you print it out as an .html file I can open it in my browser and read it plenty easily. It works for the .html file I made any way, and its formatted nicely and everything. Hopefully this helps.

**Comment by danilasokratov** [comment]
@AdamK42 I've added an html version, tell me if that works!

**Comment by AdamK42** [comment]
@danilasokratov It appears to work plenty well! Will give it a look over now.

**Comment by AdamK42** [comment]
@danilasokratov I think your lab looks pretty good overall even though I have a lot of notes. I think just about all of them are on some ways that I would clean up presentation, since your code looks pretty good to me. Or at least, it looks similar to mine. Please @me if you have any questions, I get notifications to my phone so I can answer pretty much as quickly as texting.

## A little statistics

### Part 1C.
* For this section, you never get a z-score / sigma of 5 or close, it goes from 1 to 2 to infinite. I'm not sure that this is what the lab wanted. I think the probability for a sigma of 5 is about 0.9999 for the decimal place you've rounded to, I'm pretty sure you'll have to floor round for it to work.
### Part 2
* I would probably slap a semi colon after a lot of these lines. The console output doesn't look very nice, and I think we are partially graded on presentation.
* It might also be nice to get some comments on what the values you are tweaking mean and what we should expect out of these parameters before seeing the plot. Again, this is just a presentation note.
### Part 3
* I would probably label each problem so that it is easier to see each section being done 1 to 1 with the lab file.
* For C: doesn't the cdf() integrate from the right inwards?
* For D and E: The comments in this section look like what I would want included in Part 2. Something simple that explains the numbers you are plugging in.
### Part 4
* This section looks pretty good. I would probably explicitly state the predictions you reference at the end at the beginning just so it doesn't read like you are justifying answers after you get them.

## Non-continuous distributions

### Part 1B. 
* I am not sure I understand what the rows represent in your grid of plots. The tops are with a smaller x range I assume, but what is the range for the top ones?
### Part 1C.
* The specific poisson distribution you use seems a little ambiguous to me. What are the parameters applied to this one?
* I think your question is clear up to the "if higher is signal-like..." line. After that I'm a little confused as to what you are saying.
* I think it would be useful to explain what a negative small sigma means as the answer to this question. 
### Part 1D.
* I am not sure what you mean by taking an average does not necessarily yield something of meaningful value. My interpretation of discrete probabilities/sigmas was that there was a known precision to the sigma. Is this the same thing as what you said, or am I confused?

**Comment by danilasokratov** [comment]
Thanks for the comments!

I think in part 3C, it does integrate left-to-right, since I received higher probabilities for higher selected values, meaning that it would be integrating more of the distribution.

The rows were just a difference in normal vs log plots (bottom are log plots). I'll put that in the titles, thanks!

By "something not being of meaningful value" I meant that because each measurement is discrete, an average of those measurements does not have to be discrete, and in general will be continuous. So, for example, if there were 31 trials to count how many events happened (say in a radiation experiment), and then one were to average over those 31 trials, it is quite possible that one would get an average value of counts that is not an integer, but it doesn't make sense to have 9.1 events.

I've added a response to the comments. Thanks for the help!

**Comment by danilasokratov** [comment]
@sfzhu I think I'm ready to submit! I believe both the mlx and the html files should be submitted.

**Pull request merged**
