### PR TITLE
Lab2

### PR DESCRIPTION
**Pull request by danilasokratov**
@AdamK42 I'm going to create this pull request, but I'm still polishing up my stuff for problem 4. I'll provide comments to you tomorrow, I hope.

### CODE REVIEW

**Comment by danilasokratov** [comment]
@AdamK42 Well, I will provide comments tomorrow, I guess I hope earlier than later.

**Comment by danilasokratov** [comment]
@AdamK42 I believe my submission is complete. I think I worked out my sigmas in problems 3C and 4, so they should be good for review now.

**Comment by AdamK42** [comment]
I don't really have much to add to your lab. I am not thoroughly convinced by your explanation for problem 3C, but as I do not have a better explanation then yours, I don't know if I can add anything. This seems like decent work and explanations to me. The formatting could maybe use a little work, as some of your titles are overlapping like in your grid of Rayleigh distributions. I think that's about all that I noticed though, the rest of it makes sense to me.

**Comment by AdamK42** [comment]
Looking back at your work again, what is pdfCheck doing in problem 1D? As far as I can tell it serves no purpose.

**Comment by danilasokratov** [comment]
@sfzhu I forgot to mention you. My submission should be done.

**Comment by sfzhu** [comment]
Very good!

**Pull request merged**
